channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==2.22.0
  - attr==0.3.1
  - attrs==25.3.0
  - colorama==0.4.4
  - google-cloud-logging==3.12.1
  - google-cloud-storage==2.19.0
  - jinja2==3.1.6
  - linkify-it-py==2.0.3
  - numpy==1.26.4
  - pandas==2.2.3
  - spacy==3.8.5
name: mlflow-env
